name: My first workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"

  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Bye
        run: echo "Bye"
